#!/usr/bin/env bash

# Use timestamped storage volume so that test data is removed when container is stopped
exec docker run --detach --rm \
  -p 9000:8333 \
  --name seaweedfs \
  -e AWS_ACCESS_KEY_ID=minioadmin \
  -e AWS_SECRET_ACCESS_KEY=minioadmin \
  -e S3_BUCKET=pyactivestorage \
  chrislusf/seaweedfs
