#!/usr/bin/env bash

# Use timestamped storage volume so that test data is removed when container is stopped
exec docker run --detach --rm \
  -p 9000:8333 \
  --name seaweedfs \
  -e AWS_ACCESS_KEY_ID=admin \
  -e AWS_SECRET_ACCESS_KEY=secret \
  -e S3_BUCKET=test \
  chrislusf/seaweedfs
